# Generated by Django 4.0.3 on 2023-09-30 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
