# Generated by Django 4.0.3 on 2023-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_resource_resourcetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partnerUrl',
            field=models.URLField(default='', null=True, verbose_name='partnerUrl'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='abbreviations',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='abbreviations'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='country',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='role',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
