# Generated by Django 4.0.3 on 2023-09-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='newsApp.post'),
        ),
    ]
