# Generated by Django 4.0.3 on 2023-10-05 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_alter_banner_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', embed_video.fields.EmbedVideoField()),
                ('postUrl', models.URLField(verbose_name='postUrl')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='MediaPgTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.TextField(verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='newsApp.mediapg')),
            ],
            options={
                'verbose_name': 'media pg Translation',
                'db_table': 'newsApp_mediapg_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
