# Generated by Django 4.0.3 on 2023-10-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_mediapg_mediapgtranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='post',
        ),
    ]
