# Generated by Django 4.0.3 on 2023-11-07 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_remove_banner_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
    ]
