# Generated by Django 4.0.3 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_alter_posttranslation_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.RemoveField(
            model_name='mediapg',
            name='postUrl',
        ),
        migrations.AddField(
            model_name='mediapg',
            name='postUrl',
            field=models.ManyToManyField(to='newsApp.urllink'),
        ),
    ]
