# Generated by Django 4.0.3 on 2023-11-07 14:22

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_urllink_remove_mediapg_posturl_mediapg_posturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapg',
            name='postUrl',
            field=models.ManyToManyField(blank=True, null=True, to='newsApp.urllink'),
        ),
        migrations.AlterField(
            model_name='mediapg',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
