# Generated by Django 4.0.3 on 2023-11-07 14:51

import ckeditor.fields
from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_alter_mediapg_posturl_alter_mediapg_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapg',
            name='postUrl',
        ),
        migrations.AddField(
            model_name='mediapg',
            name='content',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='postUrl'),
        ),
        migrations.AlterField(
            model_name='mediapg',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.DeleteModel(
            name='URLLink',
        ),
    ]
