# Generated by Django 4.0.3 on 2023-11-07 14:57

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0009_remove_mediapg_posturl_mediapg_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapg',
            name='url',
            field=embed_video.fields.EmbedVideoField(verbose_name='Video url'),
        ),
    ]
