# Generated by Django 4.0.3 on 2023-11-09 07:07

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0011_alter_mediapg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapg',
            name='content',
            field=django_jsonform.models.fields.JSONField(null=True),
        ),
    ]
